## Creating Basic Arrays

In [1]:
# import the numpy library
import numpy as np

In [2]:
# 1d array
x1 = np.array([3,4,5])
print(x1)

[3 4 5]


In [3]:
# 2d array
x2 = np.array([[3,4,5], [6,7,8]])
print(x2)

[[3 4 5]
 [6 7 8]]


In [11]:
# 3d array
x3 = np.array([[[3,4,5], [6,7,8], [9,10,11]]])
print(x3)

[[[ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


## Adding, removing, and sorting elements

In [5]:
# adding
a = np.array([4,6,1])

# add multiple valuesto the end of the array
b = np.append(a, [11,8,2])
print(b)

[ 4  6  1 11  8  2]


In [6]:
# removing
# remove the second element
c = np.delete(b, 1)
print(c)

[ 4  1 11  8  2]


In [7]:
# sorting 
# sort array b
d = np.sort(b)
print(d)

[ 1  2  4  6  8 11]


## shape and size of an array

In [12]:
# Let's take the example of ndarray x3
print(f"dimension of x3: {x3.ndim}")
print(f"shape of x3: {x3.shape}")
print(f"size of x3: {x3.size}")

dimension of x3: 3
shape of x3: (1, 3, 3)
size of x3: 9


## Reshaping an array