## Creating Basic Arrays

In [2]:
# import the numpy library
import numpy as np

In [2]:
# 1d array
x1 = np.array([3,4,5])
print(x1)

[3 4 5]


In [3]:
# 2d array
x2 = np.array([[3,4,5], [6,7,8]])
print(x2)

[[3 4 5]
 [6 7 8]]


In [11]:
# 3d array
x3 = np.array([[[3,4,5], [6,7,8], [9,10,11]]])
print(x3)

[[[ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


## Adding, removing, and sorting elements

In [5]:
# adding
a = np.array([4,6,1])

# add multiple valuesto the end of the array
b = np.append(a, [11,8,2])
print(b)

[ 4  6  1 11  8  2]


In [6]:
# removing
# remove the second element
c = np.delete(b, 1)
print(c)

[ 4  1 11  8  2]


In [7]:
# sorting 
# sort array b
d = np.sort(b)
print(d)

[ 1  2  4  6  8 11]


## shape and size of an array

In [12]:
# Let's take the example of ndarray x3
print(f"dimension of x3: {x3.ndim}")
print(f"shape of x3: {x3.shape}")
print(f"size of x3: {x3.size}")

dimension of x3: 3
shape of x3: (1, 3, 3)
size of x3: 9


## Reshaping an array

In [8]:
# reshape to (3,3)
x4 = np.array([5,6,7,8,9,10,5,6,1])

x5 = x4.reshape(3,3)
print(x5)

[[ 5  6  7]
 [ 8  9 10]
 [ 5  6  1]]


## Converting a 1D array into a 2D array

In [10]:
# x4 is a 1d array
# we convert to 2d array
print(f"shape of x4: {x4.shape}")

x7 = x4[np.newaxis, :]
print(f"shape of x7: {x7.shape}")

shape of x4: (9,)
shape of x7: (1, 9)


## Indexing and Slicing

In [13]:
# we index and slice x4
print(f"get the second element: {x4[1]}")
print(f"get the last element: {x4[-1]}")
print(f"get elements btwn 2nd and 4th: {x4[1:3]}") # slicing

get the second element: 6
get the last element: 1
get elements btwn 2nd and 4th: [6 7]


## Creating an array from existing data

In [11]:
# create a new array from two arrays
a1 = np.array([[1,2,5],
               [8,6,8]])
               
a2 = np.array([[6,5,3],
               [3,3,1]])

# using vstack to stack them vertically
np.vstack((a1, a2))

array([[1, 2, 5],
       [8, 6, 8],
       [6, 5, 3],
       [3, 3, 1]])

In [12]:
# stacking them horizontal
a1 = np.array([[1,2,3],
               [8,6,3]])
               
a2 = np.array([[6,5,3],
               [3,3,1]])

np.hstack((a1, a2))

array([[1, 2, 3, 6, 5, 3],
       [8, 6, 3, 3, 3, 1]])

## Basic Operations

In [13]:
# 2 example arrays
y1 = np.array([7,3,4])
y2 = np.array([2,2,2])

print(f"addition: {y1+y1}") 
print(f"subtraction: {y1-y2}")
print(f"multiplication: {y1*y2}")
print(f"Division: {y1/y2}")

addition: [14  6  8]
subtraction: [5 1 2]
multiplication: [14  6  8]
Division: [3.5 1.5 2. ]


## Broadcasting

In [15]:
# create a matrix
y3 = np.array([[5,8,6],
              [2,6,9]])

print(f"multiplication by a scalar: {y3*4}")
print(f"maximum: {y3.max()}")
print(f"minimum: {y3.min()}")
print(f"addition: {y3.sum()}")

multiplication by a scalar: [[20 32 24]
 [ 8 24 36]]
maximum: 9
minimum: 2
addition: 36


## Creating Matrices

In [4]:
# creating a 3D matrix
m1 = np.array([[[1, 6, 5], [4, 5, 13]], [[1, 1, 1], [13, 6, 98]]])
print(m1)

[[[ 1  6  5]
  [ 4  5 13]]

 [[ 1  1  1]
  [13  6 98]]]


## Getting Unique items and counts

In [7]:
# consider this array
m2 = np.array([7,4,4,4,1,1,2,3,6])

#getting unique values/items
print(f"unique values: {np.unique(m2)}")

# get value counts
print(f"value counts: {np.unique(m2, return_counts=True)}")

unique values: [1 2 3 4 6 7]
value counts: (array([1, 2, 3, 4, 6, 7]), array([2, 1, 1, 3, 1, 1], dtype=int64))


## Transposing and reshaping a matrix

In [11]:
# consider this array
m3 = np.array([2,8,10,2,105,99])

# reshape
print(m3.reshape((2,3)))

[[  2   8  10]
 [  2 105  99]]


In [12]:
# transpose
print(m3.reshape((2,3)).T)

[[  2   2]
 [  8 105]
 [ 10  99]]
