## Creating Basic Arrays

In [2]:
# import the numpy library
import numpy as np

In [2]:
# 1d array
x1 = np.array([3,4,5])
print(x1)

[3 4 5]


In [3]:
# 2d array
x2 = np.array([[3,4,5], [6,7,8]])
print(x2)

[[3 4 5]
 [6 7 8]]


In [11]:
# 3d array
x3 = np.array([[[3,4,5], [6,7,8], [9,10,11]]])
print(x3)

[[[ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


## Adding, removing, and sorting elements

In [5]:
# adding
a = np.array([4,6,1])

# add multiple valuesto the end of the array
b = np.append(a, [11,8,2])
print(b)

[ 4  6  1 11  8  2]


In [6]:
# removing
# remove the second element
c = np.delete(b, 1)
print(c)

[ 4  1 11  8  2]


In [7]:
# sorting 
# sort array b
d = np.sort(b)
print(d)

[ 1  2  4  6  8 11]


## shape and size of an array

In [12]:
# Let's take the example of ndarray x3
print(f"dimension of x3: {x3.ndim}")
print(f"shape of x3: {x3.shape}")
print(f"size of x3: {x3.size}")

dimension of x3: 3
shape of x3: (1, 3, 3)
size of x3: 9


## Reshaping an array

In [8]:
# reshape to (3,3)
x4 = np.array([5,6,7,8,9,10,5,6,1])

x5 = x4.reshape(3,3)
print(x5)

[[ 5  6  7]
 [ 8  9 10]
 [ 5  6  1]]


## Converting a 1D array into a 2D array

In [10]:
# x4 is a 1d array
# we convert to 2d array
print(f"shape of x4: {x4.shape}")

x7 = x4[np.newaxis, :]
print(f"shape of x7: {x7.shape}")

shape of x4: (9,)
shape of x7: (1, 9)


## Indexing and Slicing

In [13]:
# we index and slice x4
print(f"get the second element: {x4[1]}")
print(f"get the last element: {x4[-1]}")
print(f"get elements btwn 2nd and 4th: {x4[1:3]}") # slicing

get the second element: 6
get the last element: 1
get elements btwn 2nd and 4th: [6 7]
